import type { NextPage } from "next";
import Head from "next/head";
import Feed from "./Feed";
import NewFeed from "./newFeed";
import { getSession, signOut } from 'next-auth/react';
import { trpc } from "../utilis/trpc";


// export async function getServerSideProps(context:any) {
//   const session = await getSession(context);

//   if (!session) {
//       return {
//           redirect: {
//               destination: '/Signup',
//               permanent: false,
//           },
//       };
//   }

//   return {
//       props: { user: session.user },
//   };
// }

const Home: NextPage = () => {
  // const {data,error,isLoading}=trpc.useQuery(['hello'])

  // if(isLoading){
  //   return <p>Loading...</p>
  // }
  // if(error){
  //   return <div>{JSON.stringify(error)}</div>
  // }
  return (
    <>
      <Head>
        <title>Community</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NewFeed/>
          {/* <Feed /> */}
          {/* <div>{JSON.stringify(data)}</div> */}
    </>
  );
};

export default Home;
