import { useState } from "react";
import Head from "next/head";
import Sidebar from "./Sidebar";
import { useStateContext } from "../context/context";
type Props = {
  children: React.ReactNode;
};

const Layout = (props: Props) => {
  const {show, setShow} = useStateContext();
  return (
    <>
      <Head>
        <title>Community</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex m-0 min-h-screen   ">
        <div className="lg:w-[14%] lg:mr-12 xl:mr-3 2xl:mr-0 md:mr-8 self-start lg:self-start">
          <Sidebar setShow={setShow} show={show} />
        </div>
        <div className=" w-[70%]">{props.children}</div>
      </main>
    </>
  );
};

export default Layout;
